name: check for a new version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'

env:
  NuGet_ApiKey: ${{ secrets.NUGET_API_KEY }}

jobs:
  do-check:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set github user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Do Check
        uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1.4.1
        with:
          script-path: build.cake
          target: CI
