name: check for a new version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * *'

env:
  NuGet_ApiKey: ${{ secrets.NUGET_API_KEY }}

jobs:
  do-check:
    runs-on: windows-latest 
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v3
      - name: Do Check
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: build.cake
          target: CI
